const constants = {
    ADD_BRANCH: 'ADD_BRANCH',
    INIT_BRANCH_STATE: 'INIT_BRANCH_STATE',
    UPDATE_BRANCH: 'UPDATE_BRANCH',
    DELETE_BRANCH: 'DELETE_BRANCH',
    INIT_SETTINGS_STATE : 'INIT_SETTINGS_STATE',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
}

export default constants;
